web: uvicorn server:app --host 0.0.0.0 --port $PORT
worker: celery -A celery_app:celery_app worker --loglevel=info --concurrency=2 -Q default,media,content,video
beat: celery -A celery_app:celery_app beat --loglevel=info --scheduler celery.beat:PersistentScheduler
