import { useEffect } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

export default function TermsOfService() {
  useEffect(() => { document.title = "Terms of Service — ThookAI"; }, []);

  return (
    <div className="min-h-screen bg-[#050505] text-zinc-300">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link to="/" className="inline-flex items-center gap-2 text-zinc-500 hover:text-lime text-sm mb-8 transition-colors">
          <ArrowLeft size={14} /> Back to ThookAI
        </Link>

        <h1 className="font-display font-bold text-3xl text-white mb-2">Terms of Service</h1>
        <p className="text-zinc-500 text-sm mb-8">Last updated: April 2026</p>

        <div className="space-y-6 text-sm leading-relaxed">
          <section>
            <h2 className="text-white font-semibold text-lg mb-2">1. Acceptance of Terms</h2>
            <p>By accessing or using ThookAI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-2">2. Description of Service</h2>
            <p>ThookAI is an AI-powered content creation platform that generates social media content based on your personal voice profile ("Persona Engine"). The Service includes content generation, scheduling, publishing, and analytics features.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-2">3. Account Responsibilities</h2>
            <ul className="list-disc ml-5 space-y-1">
              <li>You must provide accurate registration information</li>
              <li>You are responsible for maintaining the security of your account</li>
              <li>You must not share your account credentials</li>
              <li>You must be at least 18 years old to use the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-2">4. Content Ownership</h2>
            <p>You retain ownership of all content you create using ThookAI. We do not claim any intellectual property rights over your generated content. You grant us a limited license to process your data solely for providing the Service.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-2">5. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc ml-5 mt-2 space-y-1">
              <li>Generate content that is illegal, harmful, or violates others' rights</li>
              <li>Impersonate another person or entity</li>
              <li>Attempt to bypass rate limits or security measures</li>
              <li>Reverse engineer or scrape the Service</li>
              <li>Generate spam or misleading content</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-2">6. Credits & Billing</h2>
            <ul className="list-disc ml-5 space-y-1">
              <li>Credits are consumed when generating content, images, videos, and other AI operations</li>
              <li>Unused credits do not roll over between billing periods</li>
              <li>Credits are refunded automatically if content generation fails</li>
              <li>Subscriptions can be cancelled at any time via Settings</li>
              <li>Refunds for purchases are handled on a case-by-case basis</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-2">7. AI-Generated Content Disclaimer</h2>
            <p>Content generated by ThookAI is created by artificial intelligence and may contain inaccuracies. You are responsible for reviewing all generated content before publishing. ThookAI is not liable for any consequences of publishing AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-2">8. Limitation of Liability</h2>
            <p>ThookAI is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-2">9. Changes to Terms</h2>
            <p>We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-2">10. Contact</h2>
            <p>For questions about these terms, contact us at <a href="mailto:legal@thookai.com" className="text-lime hover:underline">legal@thookai.com</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
